name: CI Job
on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    name: A job to run in docker container
    steps:
      - name: Run action step
        uses: actions/checkout@v2

      - name: Setup environments
        env:
        LOGIN: ${{ secrets.LOGIN }}
        PASSWORD: ${{ secrets.PASSWORD }}
        HTTP_PORT: ${{ secrets.HTTP_PORT }}
        HTTPS_PORT: ${{ secrets.HTTPS_PORT }}
        TLS_CERT_PATH: ${{ secrets.TLS_CERT_PATH }}
        TLS_KEY_PATH: ${{ secrets.TLS_KEY_PATH}}
        run: |
          echo "LOGIN=$LOGIN" >> .env
          echo "PASSWORD=$PASSWORD" >> .env
          echo "HTTP_PORT=$HTTP_PORT" >> .env
          echo "HTTPS_PORT=$HTTPS_PORT" >> .env
          echo "TLS_CERT_PATH=$TLS_CERT_PATH" >> .env
          echo "TLS_KEY_PATH=$TLS_KEY_PATH" >> .env

      - name: Run test and save coverage profile
        run: go test -race -v -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
