name: Tests
on: [push, pull_request]

jobs:
  run_tests:
    strategy:
      matrix:
        go-version: [1.20.x, 1.21.x, 1.22.x, 1.23.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup environments
        env:
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          HTTP_PORT: ${{ secrets.HTTP_PORT }}
          HTTPS_PORT: ${{ secrets.HTTPS_PORT }}
          TLS_CERT_PATH: ${{ secrets.TLS_CERT_PATH }}
          TLS_KEY_PATH: ${{ secrets.TLS_KEY_PATH}}
          FORCED_TLS: ${{ secrets.FORCED_TLS}}
        run: |
          echo "LOGIN=$LOGIN" >> .env
          echo "PASSWORD=$PASSWORD" >> .env
          echo "SECRET_KEY=$SECRET_KEY" >> .env
          echo "HTTP_PORT=$HTTP_PORT" >> .env
          echo "HTTPS_PORT=$HTTPS_PORT" >> .env
          echo "TLS_CERT_PATH=$TLS_CERT_PATH" >> .env
          echo "TLS_KEY_PATH=$TLS_KEY_PATH" >> .env
          echo "FORCED_TLS=$FORCED_TLS" >> .env

      - name: Run test and save coverage profile
        run: go test -race -v -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt

  deploy:
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to Docker Registry
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: iqhater/auth_cookie_example:latest
